import tailwindAnimate from "tailwindcss-animate";
import typography from "@tailwindcss/typography";

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                "surface-bright": "#faf8ff",
                "inverse-primary": "#b8c3ff",
                "primary-container": "#2e5bff",
                "on-secondary-fixed-variant": "#304189",
                "surface-dim": "#d9d9e3",
                "outline": "#747688",
                "on-tertiary-container": "#c8fec9",
                "on-tertiary-fixed-variant": "#20502a",
                "surface": "#faf8ff",
                "secondary-fixed-dim": "#b8c3ff",
                "outline-variant": "#c4c5d9",
                "error": "#ba1a1a",
                "on-tertiary-fixed": "#002109",
                "secondary": "#4959a3",
                "surface-container-low": "#f3f3fd",
                "on-primary": "#ffffff",
                "inverse-on-surface": "#f0f0fa",
                "on-secondary-fixed": "#001356",
                "surface-variant": "#e2e2ec",
                "primary-fixed-dim": "#b8c3ff",
                "tertiary-fixed-dim": "#9fd3a2",
                "on-surface-variant": "#434656",
                "on-tertiary": "#ffffff",
                "tertiary-container": "#47784e",
                "surface-container-high": "#e7e7f1",
                "error-container": "#ffdad6",
                "primary": "#0040e0",
                "on-primary-container": "#efefff",
                "on-background": "#191b22",
                "on-error": "#ffffff",
                "on-secondary": "#ffffff",
                "inverse-surface": "#2e3038",
                "on-secondary-container": "#2f4088",
                "on-error-container": "#93000a",
                "surface-container-lowest": "#ffffff",
                "surface-container-highest": "#e2e2ec",
                "secondary-container": "#9fafff",
                "on-primary-fixed-variant": "#0035be",
                "tertiary-fixed": "#baf0bc",
                "tertiary": "#2f5f37",
                "primary-fixed": "#dde1ff",
                "on-primary-fixed": "#001356",
                "surface-tint": "#124af0",
                "secondary-fixed": "#dde1ff",
                "on-surface": "#191b22",
                "background": "#faf8ff",
                "surface-container": "#ededf7",
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                foreground: "hsl(var(--foreground))",
            },
            borderRadius: {
                DEFAULT: "1rem",
                lg: "2rem",
                xl: "3rem",
                full: "9999px",
            },
            fontFamily: {
                headline: ["Plus Jakarta Sans", "sans-serif"],
                body: ["Inter", "sans-serif"],
                label: ["Inter", "sans-serif"],
            },
            keyframes: {
                "accordion-down": {
                    from: { height: 0 },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: 0 },
                },
                "fade-in": {
                    "0%": { opacity: 0 },
                    "100%": { opacity: 1 },
                },
                "slide-in-from-bottom": {
                    "0%": { transform: "translateY(20px)", opacity: 0 },
                    "100%": { transform: "translateY(0)", opacity: 1 },
                },
                "glow-pulse": {
                    "0%, 100%": { boxShadow: "0 0 20px hsla(var(--primary), 0.3)" },
                    "50%": { boxShadow: "0 0 30px hsla(var(--primary), 0.5)" },
                },
                "float": {
                    "0%, 100%": { transform: "translateY(0)" },
                    "50%": { transform: "translateY(-8px)" },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
                "fade-in": "fade-in 0.5s ease-out",
                "slide-up": "slide-in-from-bottom 0.5s ease-out",
                "glow-pulse": "glow-pulse 2s ease-in-out infinite",
                "float": "float 4s ease-in-out infinite",
            },
        },
    },
    plugins: [
        tailwindAnimate,
        typography,
    ],
}
